APP_TITLE = "RABBITS CTF"
MONGODB_DB = "mahjongdb"
OAUTH_CACHE_TYPE = "simple"
CACHE_TYPE = "simple"
MAHJONG_CACHE_DIR = "/tmp/mahjong/cache"

LOGIN_PROVIDERS = ["PSU"]
AUTHLIB_SSL_VERIFY_PSU = False
