APP_TITLE = "RABBITS CTF"
MONGODB_DB = "noppakaodb"
OAUTH_CACHE_TYPE = "simple"
CACHE_TYPE = "SimpleCache"
NOPPHAKAO_CACHE_DIR = "/tmp/noppakao/cache"

LOGIN_PROVIDERS = ["PSU"]
AUTHLIB_SSL_VERIFY_PSU = False
